### ISSUE TITLE
Manipulate messages

### ISSUE THREAD

**Issue by sanderux** [bluenviron/mavp2p#3]
In this section i have added an additional topic (MessageVideoStreamInformation)
https://github.com/aler9/mavp2p/blob/main/main.go#L144-L153

When i do that, the topic no longer proxies to the other nodes.
My goal is to take a message and change some values.

@aler9  Any ideas?

**Comment by aler9** [comment]
Hello, all incoming messages are routed to the other nodes, except the ones that can't be decoded.
If you added a message definition to the dialect, and incoming messages can't be decoded anymore, it means that the message definition that you added doesn't match incoming message. Make sure that the definition is correct.
