### ISSUE TITLE
Heartbeat componentID

### ISSUE THREAD

**Issue by sanderux** [bluenviron/mavp2p#46]
@aler9 

Hi Allessandro,

You allow setting systemID, but not componentID. Currently the heartbeats default to componentID=1 which is an autopilot. This led to some confusion in other mavlink systems. 191 would make more sense as default value (MAV_COMP_ID_ONBOARD_COMPUTER). 

See https://mavlink.io/en/messages/minimal.html

**Comment by aler9** [comment]
Hello Sander, i changed the default component ID to 191, added `--hb-componentid` flag and released v1.2.0.
